"use client";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Plus } from "lucide-react";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { api } from "@/shared/api/client";
import { useTenant } from "@/shared/components/providers";
import { Button,Card,Empty,Field,Input,Select } from "@/shared/components/ui";
import type { Location,Resource,Service } from "@/shared/types/domain";
import { money } from "@/shared/lib/utils";

type Kind="locations"|"services"|"resources";
const labels={locations:["Sedes","Nueva sede"],services:["Servicios","Nuevo servicio"],resources:["Recursos","Nuevo recurso"]} as const;
export function CatalogManager({kind}:{kind:Kind}){
 const {tenantId}=useTenant(); const qc=useQueryClient(); const [form,setForm]=useState<Record<string,string>>({timezone:"America/Lima",durationMinutes:"30",price:"0",type:"STAFF",capacity:"1"});
 const list=useQuery({queryKey:[kind,tenantId],queryFn:()=>api<(Location|Service|Resource)[]>(`/api/v1/${kind}`,{tenantId}),enabled:!!tenantId});
 const locations=useQuery({queryKey:["locations",tenantId],queryFn:()=>api<Location[]>("/api/v1/locations",{tenantId}),enabled:!!tenantId&&kind==="resources"});
 const create=useMutation({mutationFn:(body:unknown)=>api(`/${"api/v1"}/${kind}`,{tenantId,method:"POST",body:JSON.stringify(body)}),onSuccess:()=>{qc.invalidateQueries({queryKey:[kind,tenantId]});toast.success("Guardado correctamente");setForm({timezone:"America/Lima",durationMinutes:"30",price:"0",type:"STAFF",capacity:"1"});},onError:(e:Error)=>toast.error(e.message)});
 const submit=(e:FormEvent)=>{e.preventDefault();const body=kind==="locations"?{name:form.name,address:form.address,timezone:form.timezone}:kind==="services"?{name:form.name,description:form.description,durationMinutes:Number(form.durationMinutes),price:Number(form.price),publicVisible:true}:{name:form.name,locationId:form.locationId,type:form.type,capacity:Number(form.capacity)};create.mutate(body)};
 if(!tenantId)return <Empty title="Selecciona una empresa" description="Define el tenant activo antes de administrar el catálogo."/>;
 const meta=(item:Location|Service|Resource)=>{if("durationMinutes" in item)return `${item.durationMinutes} min · ${money(item.price)}`;if("type" in item)return `${item.type} · capacidad ${item.capacity}`;return item.address||item.timezone};
 return <div className="grid gap-6 lg:grid-cols-[1fr_390px]"><Card><h2 className="text-2xl font-semibold">{labels[kind][0]}</h2><div className="mt-5 grid gap-3">{list.data?.length?list.data.map(item=><div key={item.id} className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><div><p className="font-bold text-slate-900">{item.name}</p><p className="text-sm text-slate-500">{meta(item)}</p></div><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-800">Activo</span></div>):<Empty title="Aún no hay registros" description="Crea el primero desde el formulario."/>}</div></Card><Card><div className="flex items-center gap-2"><Plus className="text-teal-700"/><h2 className="text-2xl font-semibold">{labels[kind][1]}</h2></div><form onSubmit={submit} className="mt-5 grid gap-4"><Field label="Nombre"><Input required value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})}/></Field>{kind==="locations"&&<><Field label="Dirección"><Input value={form.address||""} onChange={e=>setForm({...form,address:e.target.value})}/></Field><Field label="Zona horaria"><Input required value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></Field></>}{kind==="services"&&<><Field label="Descripción"><Input value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Duración (min)"><Input type="number" min="5" required value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:e.target.value})}/></Field><Field label="Precio"><Input type="number" min="0" step="0.01" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></Field></div></>}{kind==="resources"&&<><Field label="Sede"><Select required value={form.locationId||""} onChange={e=>setForm({...form,locationId:e.target.value})}><option value="">Seleccionar</option>{locations.data?.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Select></Field><div className="grid grid-cols-2 gap-3"><Field label="Tipo"><Select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{["STAFF","SPACE","ASSET","CAPACITY"].map(v=><option key={v}>{v}</option>)}</Select></Field><Field label="Capacidad"><Input type="number" min="1" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></Field></div></>}<Button disabled={create.isPending}>{create.isPending?"Guardando…":"Guardar"}</Button></form></Card></div>
}
