"use client";
import {useQuery} from "@tanstack/react-query";
import {Building2,CalendarDays,LogOut,Users} from "lucide-react";
import {useRouter} from "next/navigation";
import {useEffect} from "react";
import {api} from "@/shared/api/client";
import {useTenant} from "@/shared/components/providers";
import {Badge,Card} from "@/shared/components/ui";
import type {Tenant} from "@/shared/types/domain";
type Overview={tenants:number;users:number;bookings:number;activeSubscriptions:number};
type User={id:string;email:string;fullName:string;active:boolean;platformRole?:string};
export function PlatformDashboard(){const {session,ready,logout}=useTenant();const router=useRouter();useEffect(()=>{if(ready&&session?.role!=="PLATFORM_ADMIN")router.replace(session?"/admin":"/login")},[ready,session,router]);const enabled=session?.role==="PLATFORM_ADMIN";const overview=useQuery({queryKey:["platform-overview"],queryFn:()=>api<Overview>("/api/v1/platform/overview"),enabled});const tenants=useQuery({queryKey:["platform-tenants"],queryFn:()=>api<Tenant[]>("/api/v1/platform/tenants"),enabled});const users=useQuery({queryKey:["platform-users"],queryFn:()=>api<User[]>("/api/v1/platform/users"),enabled});if(!enabled)return <main className="grid min-h-screen place-items-center">Validando acceso…</main>;const stats=[["Empresas",overview.data?.tenants??0,Building2],["Usuarios",overview.data?.users??0,Users],["Reservas",overview.data?.bookings??0,CalendarDays]] as const;return <main className="min-h-screen bg-slate-50"><header className="border-b bg-slate-950 text-white"><div className="shell flex h-20 items-center justify-between"><div><p className="font-extrabold">turno<span className="text-emerald-400">.</span></p><p className="text-xs text-slate-400">Administración de plataforma · solo lectura</p></div><button onClick={()=>{logout();router.replace("/login")}} className="flex items-center gap-2 text-sm"><LogOut size={16}/>Salir</button></div></header><div className="shell py-10"><h1 className="text-4xl font-semibold">Vista global</h1><div className="mt-7 grid gap-4 md:grid-cols-3">{stats.map(([label,value,Icon])=><Card key={label}><Icon className="text-teal-700"/><p className="mt-5 text-3xl font-extrabold">{value}</p><p className="text-sm text-slate-500">{label}</p></Card>)}</div><div className="mt-7 grid gap-6 xl:grid-cols-2"><Card><h2 className="text-2xl font-semibold">Empresas</h2><div className="mt-4 divide-y">{tenants.data?.map(tenant=><div key={tenant.id} className="flex items-center justify-between py-3"><div><p className="font-bold">{tenant.name}</p><p className="text-xs text-slate-500">/{tenant.slug}</p></div><Badge tone={tenant.active?"green":"amber"}>{tenant.active?"ACTIVA":"PENDIENTE"}</Badge></div>)}</div></Card><Card><h2 className="text-2xl font-semibold">Usuarios</h2><div className="mt-4 divide-y">{users.data?.map(user=><div key={user.id} className="py-3"><p className="font-bold">{user.fullName}</p><p className="text-xs text-slate-500">{user.email}</p></div>)}</div></Card></div></div></main>}
