"use client";
import {useMutation,useQuery} from "@tanstack/react-query";
import {CreditCard,LockKeyhole} from "lucide-react";
import {useRouter} from "next/navigation";
import {useEffect,useRef} from "react";
import {toast} from "sonner";
import {api} from "@/shared/api/client";
import {useTenant} from "@/shared/components/providers";
import {Button,Card} from "@/shared/components/ui";
import type {Checkout,Session} from "@/shared/types/domain";

export function PaymentPending(){const {session,ready}=useTenant();const router=useRouter();useEffect(()=>{if(ready&&!session)router.replace("/login");else if(session&&session.role!=="PENDING_COMPANY")router.replace(session.role==="PLATFORM_ADMIN"?"/plataforma":"/admin")},[ready,session,router]);if(!session?.checkout)return <main className="grid min-h-screen place-items-center"><Card>Verificando pago…</Card></main>;return <main className="grid min-h-screen place-items-center bg-[#f7f5ef] p-4"><Card className="w-full max-w-lg p-8"><CreditCard className="text-teal-700" size={36}/><p className="mt-6 text-sm font-bold uppercase tracking-widest text-teal-700">Activación de empresa</p><h1 className="mt-2 text-4xl font-semibold">Completa tu pago</h1><p className="mt-3 text-slate-600">Plan {session.checkout.plan} para {session.tenant?.name}</p><div className="mt-6 flex items-end justify-between rounded-xl bg-slate-50 p-5"><span className="text-sm text-slate-500">Total de activación</span><strong className="text-3xl">{session.checkout.currency} {session.checkout.amount}</strong></div><a href={session.checkout.checkoutUrl} className="mt-6 flex min-h-12 items-center justify-center rounded-xl bg-teal-700 px-5 font-bold text-white">Ir al checkout seguro</a><p className="mt-4 flex items-center justify-center gap-2 text-xs text-slate-500"><LockKeyhole size={14}/>La aplicación nunca recibe los datos de tu tarjeta.</p></Card></main>}

export function FakeCheckout(){const {session,setAuth}=useTenant();const router=useRouter();const checkout=session?.checkout;const initialRegistration=session?.role==="PENDING_COMPANY";const approve=useMutation({mutationFn:()=>api<Checkout>(`/api/v1/payments/${checkout?.id}/approve-dev`,{method:"POST"}),onSuccess:async()=>{const refreshed=await api<Session>("/api/v1/auth/refresh",{method:"POST",noRefresh:true});setAuth(refreshed);toast.success("Pago de desarrollo aprobado");router.replace(initialRegistration?"/admin":"/admin/plan")},onError:(e:Error)=>toast.error(e.message)});if(!checkout)return <main className="grid min-h-screen place-items-center"><Card>Checkout no disponible.</Card></main>;return <main className="grid min-h-screen place-items-center bg-slate-100 p-4"><Card className="w-full max-w-md"><p className="text-xs font-bold uppercase tracking-widest text-violet-700">Simulador local</p><h1 className="mt-2 text-3xl font-semibold">Mercado Pago (dev)</h1><p className="mt-3 text-sm text-slate-600">Esta pantalla no realiza cargos. En producción se reemplaza automáticamente por Checkout Pro.</p><div className="my-6 rounded-xl bg-violet-50 p-5"><p>Plan {checkout.plan}</p><strong className="text-3xl">{checkout.currency} {checkout.amount}</strong></div><Button className="w-full" disabled={approve.isPending} onClick={()=>approve.mutate()}>{approve.isPending?"Confirmando…":"Simular pago aprobado"}</Button></Card></main>}

export function PaymentResult(){
 const {session,ready,setAuth}=useTenant();const router=useRouter();const handled=useRef(false);
 const status=useQuery({queryKey:["payment-status"],queryFn:()=>api<Checkout>("/api/v1/payments/status"),enabled:ready&&!!session,refetchInterval:query=>query.state.data?.status==="PAID"?false:2000,retry:6});
 useEffect(()=>{if(status.data?.status!=="PAID"||handled.current)return;handled.current=true;api<Session>("/api/v1/auth/refresh",{method:"POST",noRefresh:true}).then(next=>{setAuth(next);toast.success("Pago confirmado. Tu nuevo plan ya está activo");router.replace(next.role==="PENDING_COMPANY"?"/pago/pendiente":"/admin/plan")}).catch(()=>{handled.current=false})},[router,setAuth,status.data?.status]);
 return <main className="grid min-h-screen place-items-center bg-[#f7f5ef] p-4"><Card className="max-w-lg text-center"><p className="text-sm font-bold uppercase tracking-widest text-teal-700">Mercado Pago</p><h1 className="mt-3 text-4xl font-semibold">{status.data?.status==="PAID"?"Pago confirmado":"Estamos verificando tu pago"}</h1><p className="mt-3 text-slate-600">La activación depende del webhook seguro. Esta pantalla se actualizará automáticamente cuando llegue la confirmación.</p>{status.isError&&<p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">La confirmación aún no está disponible. Puedes volver a Mi plan y continuar revisando allí.</p>}<Button className="mt-6" onClick={()=>router.replace("/admin/plan")}>Volver a Mi plan</Button></Card></main>;
}
